import { IRoomDetail } from 'interfaces/room.interface';
import { ROOMS } from './images.const';

export const ROOMS_DATA: IRoomDetail[] = [
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },{
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },{
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
  {
    room_name: 'LUXURY HOMESTAY',
    host: 'Homestay LA',
    room_type: 'Homestay',
    total_bedrooms: 2,
    price: 100,
    imageSrc: [ROOMS[0]],
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent id molestie nunc. Morbi egestas erat non elit accumsan ornare. Praesent commodo tellus in tortor porta interdum. Integer molestie fermentum justo, vestibulum tempus metus tempus ac. Donec varius nisi at ex tincidunt, iaculis porttitor ipsum tempor. Etiam quis varius nisi. Cras sed nibh sagittis, feugiat sem at, efficitur ligula. Aliquam at venenatis dui. Fusce maximus rutrum libero, sed semper velit vehicula non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ullamcorper arcu in mollis accumsan. Etiam pellentesque libero ut magna congue egestas. Proin vehicula et eros ullamcorper sagittis. In consectetur massa diam, a posuere ante efficitur sed. Sed bibendum efficitur nulla, eget maximus nibh porttitor a.',
  },
];
